version: 2.1

jobs:
  init:
    docker:
      - image: cimg/go:1.20.1
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths: project

  kind:
    docker:
      - image: cimg/go:1.20.1
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /home/circleci

      ## first we must install the kind kubernetes tool
      ## https://kind.sigs.k8s.io/

      - run:
          name: install kind
          command: |
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind


      ## now we have to build the kind cluster
      ## update the kubeconfig with network config from this kind container
      ## create a jump box within the same docker network as the kind cluster
      ## pass the kube config into the jump box
      - run:
          name: build kind cluster
          command: |

            kind create cluster
            
            KIND_CONTAINER_IP=$(docker inspect kind-control-plane | jq  .[0].NetworkSettings.Networks.kind.IPAddress -r)
            export "NEWIP=https://$KIND_CONTAINER_IP:6443"
            yq -i '.clusters[0].cluster.server = strenv(NEWIP)' ../.kube/config
            
            # create a hop box in the kind docker network
            docker run --name hopbox -p 80:80 -d --network kind nginx
            
            docker cp ../.kube/config hopbox:/
            docker exec hopbox bash -c 'mkdir /root/.kube; cp config /root/.kube' 
      

      ## install helm in the jump box and install tools to interogate the cluster
      ## install tomcat helm chart
      - run:
          name: install helm
          command: |
            
            docker exec hopbox bash -c 'curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3;
                                        chmod 700 get_helm.sh;
                                        ./get_helm.sh'
            docker exec hopbox bash -c 'helm repo add my-repo https://charts.bitnami.com/bitnami;
                                      helm install my-release my-repo/tomcat'
     

      ## install kubectl on the jump box to confirm cluster is working and tomcat chart applied
      - run:
          name: install kubectl to test
          command: |
            
            docker exec hopbox bash -c 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
            docker exec hopbox bash -c 'curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"'
            docker exec hopbox bash -c 'echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check'
            docker exec hopbox bash -c 'install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl'
            
            sleep 30
            docker exec hopbox bash -c 'kubectl get pods'

workflows:
  version: 2

  build:
    jobs:
      - init
      - kind:
          requires:
            - init